[package]
name = "model-canister-template"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.8.4"
ic-cdk = "0.7.4"
ic-cdk-macros = "0.6.10"
serde = "1.0.152"
serde_json = "1.0.93"
num-traits = "0.2.15"
